"""add param unique in field slug model ShortURL

Revision ID: f6ea36c4c998
Revises: 9aa9cd1e7296
Create Date: 2026-02-25 01:37:38.803995

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f6ea36c4c998'
down_revision: Union[str, Sequence[str], None] = '9aa9cd1e7296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_short_urls_slug", 'short_urls', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_short_urls_slug", 'short_urls', type_='unique')
    # ### end Alembic commands ###
