"""create table anonymous_clicks

Revision ID: 38997383c09b
Revises: f6ea36c4c998
Create Date: 2026-02-25 03:12:22.117539

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '38997383c09b'
down_revision: Union[str, Sequence[str], None] = 'f6ea36c4c998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'anonymous_clicks',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('short_url_id', sa.Integer(), nullable=False),
        sa.Column('session_id', sa.String(length=64), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('user_agent', sa.String(length=512), nullable=True),
        sa.Column('accept_language', sa.String(length=128), nullable=True),
        sa.Column('referrer', sa.String(length=1048), nullable=True),
        sa.Column('is_bot_suspected', sa.Boolean(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['short_url_id'],
            ['short_urls.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_anonymous_clicks_ip_address'),
        'anonymous_clicks',
        ['ip_address'],
        unique=False,
    )
    op.create_index(
        op.f('ix_anonymous_clicks_session_id'),
        'anonymous_clicks',
        ['session_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_anonymous_clicks_short_url_id'),
        'anonymous_clicks',
        ['short_url_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anonymous_clicks_short_url_id'), table_name='anonymous_clicks')
    op.drop_index(op.f('ix_anonymous_clicks_session_id'), table_name='anonymous_clicks')
    op.drop_index(op.f('ix_anonymous_clicks_ip_address'), table_name='anonymous_clicks')
    op.drop_table('anonymous_clicks')
    # ### end Alembic commands ###
